retoqueria/urls.py
# -*- coding: utf-8 -*-


"""retoqueria URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
    url(r'^admin/clientes/', include('clientes.urls')),
    url(r'^admin/funcionarios/', include('funcionarios.urls')),
    url(r'^admin/proveedores/', include('proveedores.urls')),
    url(r'^admin/materiales/', include('materiales.urls')),

    url(r'^admin/depositos/', include('depositos.urls')),
    url(r'^admin/servicios/', include('servicios.urls')),

    url(r'^admin/produccion/', include('produccion.urls')),

    url(r'^admin/ventas/', include('ventas.urls')),

    url(r'^admin/', include(admin.site.urls)), 
    url(r'^chaining/', include('smart_selects.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

servicios/urls.py
from django.conf.urls import patterns, include, url
from servicios.autocomplete import *
from servicios.views import *
from servicios.ajax import *


urlpatterns = [
    url(
        'categoriadeservicioautocomplete/$',
        CategoriaDeServicioAutocomplete.as_view(),
        name='categoriadeservicio-autocomplete',
    ),

    url(
        'telaautocomplete/$',
        TelaAutocomplete.as_view(),
        name='tela-autocomplete',
    ),

    url(
        'telaitemautocomplete/$',
        TelaItemAutocomplete.as_view(),
        name='telaitem-autocomplete',
    ),

    url(
        'servicioautocomplete/$',
        ServicioAutocomplete.as_view(),
        name='servicio-autocomplete',
    ),

    url(
        'servicio-por-categoria-autocomplete/$',
        ServicioPorCategoriaAutocomplete.as_view(),
        name='servicio-por-categoria-autocomplete',
    ),

    url('getservicio/$',get_servicio),
    url('getlistadetelasdelservicio/$',get_lista_de_telas_del_servicio),
    url('getlistadematerialesdelservicio/$', get_lista_de_materiales_del_servicio),
    url('getpreciodelservicio/$',get_precio_del_servicio),
    url(r'^get_duracion_servicio/$', get_duracion_servicio),

    url(r'^categoriadeservicio/$', CategoriaDeServicioListView.as_view(), name='categoriadeservicio_lis'),

    url(r'^tela/$', TelaListView.as_view(), name='tela_lis'),

    url(r'^servicio/(?P<pk>\d+)/detail/$', ServicioDetailView.as_view(), name='servicio_det'),
    url(r'^servicio/$', ServicioListView.as_view(), name='servicio_lis'),
    url(r'^$', servicios_presentacion),

]

ventas/urls.py
from django.conf.urls import patterns, include, url

from ventas.autocomplete import CajaAutocomplete
from ventas.reports import reporte_consolidado_pdf
from ventas.views import *


urlpatterns = [
    url(
        r'^caja-autocomplete/$',
        CajaAutocomplete.as_view(),
        name='caja-autocomplete',
    ),

    url(r'^venta/(?P<pk>\d+)/detail/$', VentaDetailView.as_view(), name='venta_det'),
    url(r'^venta/$', VentaListView.as_view(), name='venta_lis'),
    url(r'^$', ventas_presentacion),
    url(
        r'^reporte_consolidado_pdf/(?P<id>\w+)/$',
        reporte_consolidado_pdf,
        name='reporte_consolidado_pdf',
    ),
]

servicios/models.py
# -*- coding: utf-8 -*-

from django.db import models

TIPO_DE_SERVICIO = (
    ("modista", 'Modista'),
    ("costura", 'Costurera'),
)


class CategoriaDeServicio(models.Model):
    class Meta:
        verbose_name = "categoria de servicio"
        verbose_name_plural = "categorias de servicio"

    codigo = models.IntegerField(default=0)
    nombre = models.CharField(max_length=100)
    activo = models.BooleanField(default=True)

    def __unicode__(self):
        return '%s - %s' % (self.codigo, unicode(self.nombre))


class Tela(models.Model):
    nombre = models.CharField(max_length=100)
    activo = models.BooleanField(default=True)

    def __unicode__(self):
        return unicode(self.nombre)


class Servicio(models.Model):
    categoria = models.ForeignKey(CategoriaDeServicio)
    codigo = models.CharField(max_length=10)
    descripcion = models.CharField(max_length=100)
    duracion = models.IntegerField(verbose_name="duracion (en minutos)", default=0)
    es_plantilla = models.BooleanField(default=True)
    servicio_padre = models.ForeignKey('self', null=True, blank=True)
    tipo = models.CharField(max_length=10, choices=TIPO_DE_SERVICIO, default="modista")

    def __unicode__(self):
        return unicode(self.descripcion)

    def get_materiales(self):
        return DetalleDeServicioMaterial.objects.filter(servicio_id=self.id)


class DetalleDeServicioTela(models.Model):
    servicio = models.ForeignKey(Servicio)
    tela = models.ForeignKey(Tela)
    precio = models.DecimalField(max_digits=15, decimal_places=2)


class DetalleDeServicioMaterial(models.Model):
    servicio = models.ForeignKey(Servicio)
    material = models.ForeignKey("materiales.Material")
    cantidad = models.DecimalField(max_digits=15, decimal_places=2)

servicios/forms.py
from dal import autocomplete
from django import forms
from django.forms import CharField

from servicios.models import *


class ServicioForm(forms.ModelForm):
    class Meta:
        model = Servicio
        fields = ('__all__')
        widgets = {
            "categoria": autocomplete.ModelSelect2(url='categoriadeservicio-autocomplete'),
            "es_plantilla": forms.HiddenInput(),
            "servicio_padre": forms.HiddenInput(),
        }


class DetalleDeServicioTelaForm(forms.ModelForm):
    class Meta:
        model = DetalleDeServicioTela
        fields = ('__all__')
        widgets = {
            "tela": autocomplete.ModelSelect2(url='tela-autocomplete'),
            "precio": forms.TextInput(
                attrs={'style': 'text-align:right', 'size': '12', 'class': 'auto', 'data-a-sep': '.',
                       'data-a-dec': ','}),
        }


class DetalleDeServicioMaterialForm(forms.ModelForm):
    class Meta:
        model = DetalleDeServicioMaterial
        fields = ('__all__')
        widgets = {
            "material": autocomplete.ModelSelect2(url='material-autocomplete'),
            "cantidad": forms.TextInput(
                attrs={'style': 'text-align:right', 'size': '12', 'class': 'auto', 'data-a-sep': '.',
                       'data-a-dec': ','}),
        }

servicios/views.py
from django.shortcuts import render, render_to_response

from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from django.db.models import Q

from servicios.models import *
from extra.globals import *


class CategoriaDeServicioListView(ListView):
    model = CategoriaDeServicio
    template_name = "categoriadeservicio_list.html"
    paginate_by = 30

    def get_queryset(self):
        categoriasdeservicios = CategoriaDeServicio.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            categoriasdeservicios = categoriasdeservicios.filter( Q(nombre__icontains=q) | Q(id__istartswith=q) )

        return categoriasdeservicios.order_by('nombre')

    def get_context_data(self, **kwargs):
        context = super(CategoriaDeServicioListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(CategoriaDeServicioListView, self).dispatch(*args, **kwargs)


class TelaListView(ListView):
    model = Tela
    template_name = "tela_list.html"
    paginate_by = 30

    def get_queryset(self):
        telas = Tela.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            telas = telas.filter( Q(nombre__icontains=q) | Q(id__istartswith=q) )

        return telas.order_by('nombre')

    def get_context_data(self, **kwargs):
        context = super(TelaListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(TelaListView, self).dispatch(*args, **kwargs)


class ServicioListView(ListView):
    model = Servicio
    template_name = "servicio_list.html"
    paginate_by = 30

    def get_queryset(self):
        #servicios = Servicio.objects.all()
        servicios = Servicio.objects.filter(es_plantilla=True)

        q = self.request.GET.get('q', '')
        if q != '':
            servicios = servicios.filter(Q(descripcion__icontains=q) | Q(codigo__istartswith=q) )

        categoria_id=self.request.GET.get('categoria_id','')
        if categoria_id !='':
            servicios = servicios.filter(categoria_id = categoria_id)

        return servicios.order_by("descripcion")

    def get_context_data(self, **kwargs):
        context = super(ServicioListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        context['categorias'] = CategoriaDeServicio.objects.all()
        context['categoria_id'] = int(self.request.GET.get('categoria_id','')) if (self.request.GET.get('categoria_id','') != '') else ''
        return context

    def render_to_response(self, context, **response_kwargs):
        if 'excel' in self.request.GET.get('excel', ''): 

            lista_datos=[]
            datos = self.get_queryset()
            for dato in datos:
                lista_datos.append([
                    dato.categoria.nombre,
                    dato.codigo,
                    dato.descripcion,
                    dato.duracion,

                ])

            titulos=[ 
            	'Categoria',
            	'Codigo',
                'Descripcion', 
                'Duracion (en hs)', 

            ]
            return listview_to_excel(lista_datos,'Servicios',titulos)
        
        return super(ServicioListView, self).render_to_response(context, **response_kwargs)

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(ServicioListView, self).dispatch(*args, **kwargs)


class ServicioDetailView(DetailView):
    model = Servicio
    template_name = "servicio_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ServicioDetailView, self).get_context_data(**kwargs)
        context['detalle_de_servicio_tela'] = DetalleDeServicioTela.objects.filter(servicio_id=self.object.id)
        context['detalle_de_servicio_material'] = DetalleDeServicioMaterial.objects.filter(servicio_id=self.object.id)
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(ServicioDetailView, self).dispatch(*args, **kwargs)


def servicios_presentacion(request):
    context = RequestContext(request)
    titulo ="SERVICIOS"
    descripcion =".."
    return render_to_response('admin/presentacion.html', {'titulo': titulo, 'descripcion': descripcion}, context)

servicios/templates/categoriadeservicio_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
{% endblock %}

{% block extrajs %}	
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Categorias</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>
							<th style="vertical-align:middle">
								<strong> Buscar:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Nombre o ID.." name="q" value="{{ q }}">
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/servicios/categoriadeservicio" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			{% if perms.servicios.add_categoriadeservicio %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/servicios/categoriadeservicio/add/';" title="Agregar Categoria">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}

			<!--
			<button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
				<i class="fa fa-file-excel-o"></i>
			</button>
			--> 
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>ID</th>
					<th>Nombre</th>
					<th>Activo</th>
					<th>Acciones</th>
				</tr>
			</thead>

			<tbody>
				{% for categoriadeservicio in object_list %}
				<tr>
					<td>{{ categoriadeservicio.id }}</td>
					<td>{{ categoriadeservicio.nombre }}</td>
					<td>{{ categoriadeservicio.activo }}</td>

					<td>
						{% if perms.servicios.change_categoriadeservicio %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/servicios/categoriadeservicio/{{ categoriadeservicio.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.servicios.delete_categoriadeservicio %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/servicios/categoriadeservicio/{{ categoriadeservicio.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}


					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/servicios/categoriadeservicio/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/servicios/categoriadeservicio/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/servicios/categoriadeservicio/?page={{ page }}&q={{ q }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/servicios/categoriadeservicio/?page={{ page_obj.next_page_number }}&q={{ q }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/servicios/categoriadeservicio/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}

servicios/templates/servicio_detail.html
{% extends "admin/base_site.html" %}
{% load humanize %}

{% block content %}
<h1>Datos del Servicio</h1>
<table class="table table-striped table-filter" summary="Datos del Servicio.">
	<tbody>
		<tr>
			<th scope="row"> Categoria </th>
			<td> {{ object.categoria }} </td>
		</tr>

		<tr>
			<th scope="row"> Codigo </th>
			<td> {{ object.codigo }} </td>
		</tr>

		<tr>
			<th scope="row"> Descripcion </th>
			<td> {{ object.descripcion }} </td>
		</tr>

		<tr>
			<th scope="row"> Tipo </th>
			<td> {{ object.tipo }} </td>
		</tr>

	</tbody>
</table>

{% if detalle_de_servicio_tela %}
<table id="result_list" class="table table-striped table-bordered table-hover table-condensed">
	<caption><h1>Detalle del Servicio - Telas</h1></caption>

	<thead>
		<tr>
			<th>Tela</th>
			<th>Precio</th>
		</tr>
	</thead>

	<tbody>
		{% for detalle in detalle_de_servicio_tela %}
		<tr>
			<td>{{ detalle.tela }}</td>
			<td>{{ detalle.precio|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endif %}

{% if detalle_de_servicio_material %}
<table id="result_list" class="table table-striped table-bordered table-hover table-condensed">
	<caption><h1>Detalle del Servicio - Materiales</h1></caption>

	<thead>
		<tr>
			<th>Material</th>
			<th>Precio</th>
		</tr>
	</thead>

	<tbody>
		{% for detalle in detalle_de_servicio_material %}
		<tr>
			<td>{{ detalle.material }}</td>
			<td>{{ detalle.cantidad|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endif %}

<button type="button" class="btn btn-primary" onclick="window.history.back(); return false;">Volver</button>

{% endblock %}

servicios/templates/servicio_list.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>

    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
    <form class="form" method="get">
        <h1>Lista de Servicios</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Servicio:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="search-query" placeholder="Codigo o descripcion.." name="q" value="{{ q }}">
                        </td>

                        <th style="vertical-align:middle">
                            <strong> Categoria:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select class="chosen-select" data-placeholder="Seleccione un categoria.." name="categoria_id" value="{{ categoria_id }}" onchange="this.form.submit();">
                                <option value=""></option>
                                {% for categoria in categorias %}
                                    <option {% if categoria.pk == categoria_id %} selected {% endif %} value="{{ categoria.id }}">{{ categoria }}</option>
                                {% endfor %}
                            </select>
                        </td>

                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/servicios/servicio" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>

                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">

            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>

            {% if perms.servicios.add_servicio %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/servicios/servicio/add/';" title="Agregar Servicio">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}

        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>Codigo</th>
                <th>Descripcion</th>
                <th>Categoria</th>
                <th>Tipo</th>
                <th>Acciones</th>

            </tr>
            </thead>

            <tbody>
            {% for servicio in object_list %}
                <tr>
                    <td>{{ servicio.codigo }}</td>
                    <td>{{ servicio.descripcion }}</td>
                    <td>{{ servicio.categoria }}</td>
                    <td>{{ servicio.tipo }}</td>
                    <td>
                        {% if perms.servicios.change_servicio %}
                            <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/servicios/servicio/{{ servicio.id }}/';" title="Editar">
                                <i class="fa fa-pencil"></i>
                            </button>
                        {% endif %}

                        {% if perms.servicios.delete_servicio %}
                            <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/servicios/servicio/{{ servicio.id }}/delete/';" title="Borrar">
                                <i class="fa fa-minus"></i>
                            </button>
                        {% endif %}


                        <button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/servicios/servicio/{{ servicio.id }}/detail/';" title="Detalle">
                            <i class="fa fa-list-ol"></i>
                        </button>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/servicios/servicio/?page={{ page_obj.previous_page_number }}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/servicios/servicio/?page={{ page_obj.previous_page_number }}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/servicios/servicio/?page={{ page }}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/servicios/servicio/?page={{ page_obj.next_page_number }}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/servicios/servicio/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}

servicios/templates/tela_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
{% endblock %}

{% block extrajs %}	
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Telas</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>
							<th style="vertical-align:middle">
								<strong> Buscar:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Nombre o ID.." name="q" value="{{ q }}">
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/servicios/tela" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			{% if perms.servicios.add_tela %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/servicios/tela/add/';" title="Agregar Categoria">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}

			<!--
			<button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
				<i class="fa fa-file-excel-o"></i>
			</button>
			--> 
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>ID</th>
					<th>Nombre</th>
					<th>Activo</th>
					<th>Acciones</th>
				</tr>
			</thead>

			<tbody>
				{% for tela in object_list %}
				<tr>
					<td>{{ tela.id }}</td>
					<td>{{ tela.nombre }}</td>
					<td>{{ tela.activo }}</td>

					<td>
						{% if perms.servicios.change_tela %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/servicios/tela/{{ tela.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.servicios.delete_tela %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/servicios/tela/{{ tela.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}


					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/servicios/tela/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/servicios/tela/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/servicios/tela/?page={{ page }}&q={{ q }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/servicios/tela/?page={{ page_obj.next_page_number }}&q={{ q }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/servicios/tela/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}