produccion/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import permission_required

from produccion.autocomplete import *
from produccion.ajax import *
from produccion.views import *


urlpatterns = patterns('',

                       url(
                           r'^ordendetrabajo/$',
                           permission_required('produccion.ver_ot_todos')(OrdenDeTrabajoListView.as_view()),
                           name='ordendetrabajo_lis'
                       ),

                       url(
                           r'^ordendetrabajo/pendiente/$',
                           permission_required('produccion.ver_ot_pendientes')(OrdenDeTrabajoPendienteListView.as_view()),
                           name='ordendetrabajopendiente_lis'
                       ),

                       url(
                           r'^ordendetrabajo/proceso/$',
                           permission_required('produccion.ver_ot_proceso')(OrdenDeTrabajoProcesoListView.as_view()),
                           name='ordendetrabajoproceso_lis'
                       ),

                       url(
                           r'^ordendetrabajo/produccion/$',
                           permission_required('produccion.ver_ot_produccion')(OrdenDeTrabajoProduccionListView.as_view()),
                           name='ordendetrabajoproduccion_lis'
                       ),

                       url(
                           r'^ordendetrabajo/terminado/$',
                           permission_required('produccion.ver_ot_terminados')(OrdenDeTrabajoTerminadoListView.as_view()),
                           name='ordendetrabajoterminado_lis'
                       ),

                       url(
                           r'^ordendetrabajo/revisado/$',
                           permission_required('produccion.ver_ot_revisado')(OrdenDeTrabajoRevisadoListView.as_view()),
                           name='ordendetrabajorevisado_lis'
                       ),

                       url(
                           r'^ordendetrabajo/entregado/$',
                           permission_required('produccion.ver_ot_entregado')(OrdenDeTrabajoEntregadoListView.as_view()),
                           name='ordendetrabajoentregado_lis'
                       ),
                       url(
                           r'^ordendetrabajo/entregas/$',
                           permission_required('produccion.ver_ot_entregas')(
                               OrdenDeTrabajoEntregasListView.as_view()),
                           name='ordendetrabajoentregas_lis'
                       ),
                       url(
                           r'^ordendetrabajo/calendario/$',
                           permission_required('produccion.ver_ot_entregas')(
                               CalendarioDeEntregasListView.as_view()),
                           name='calendarioentregas_lis'
                       ),

                       url(
                           r'^ordendetrabajo/rechazado/$',
                           permission_required('produccion.ver_ot_rechazado')(OrdenDeTrabajoRechazadoListView.as_view()),
                           name='ordendetrabajorechazado_lis'
                       ),

                       url(
                           r'^ordendetrabajo/(?P<pk>\d+)/detail/$',
                           OrdenDeTrabajoDetailView.as_view(),
                           name='ordendetrabajo_det'
                       ),

                       url(r'^ordendetrabajo/(?P<pk>\d+)/pasarotproceso/$', pasar_ot_proceso, name='pasar_ot_proceso'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/pasarotproduccion/$', pasar_ot_produccion, name='pasar_ot_produccion'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/pasarotterminado/$', pasar_ot_terminado, name='pasar_ot_terminado'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/pasarotrevisado/$', pasar_ot_revisado, name='pasar_ot_revisado'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/pasarotentregado/$', pasar_ot_entregado, name='pasar_ot_entregado'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/pasarotrechazado/$', pasar_ot_rechazado, name='pasar_ot_rechazado'),

                       url(r'^ordendetrabajo/(?P<pk>\d+)/retrocederotpendiente/$', retroceder_ot_pendiente, name='retroceder_ot_pendiente'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/retrocederotproceso/$', retroceder_ot_proceso, name='retroceder_ot_proceso'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/retrocederotproduccion/$', retroceder_ot_produccion, name='retroceder_ot_produccion'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/retrocederotterminado/$', retroceder_ot_terminado, name='retroceder_ot_terminado'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/retrocederotrevisado/$', retroceder_ot_revisado, name='retroceder_ot_revisado'),
                       url(r'^ordendetrabajo/(?P<pk>\d+)/retrocederotentregado/$', retroceder_ot_entregado, name='retroceder_ot_entregado'),


                       url(
                           r'^ordendetrabajo/(?P<pk>\d+)/asignarmodista/$',
                           permission_required('produccion.asignar_modista')(AsignarModistaUpdateView.as_view()),
                           name='asignar_modista'
                       ),

                       url(
                           r'^ordendetrabajo/(?P<pk>\d+)/reprogramartrabajo/$',
                           permission_required('produccion.reprogramar_dot')(ReprogramarTrabajoUpdateView.as_view()),
                           name='reprogramar_trabajo'
                       ),

                       url(
                           r'^ordendetrabajoautocomplete/$',
                           OrdenDeTrabajoAutocomplete.as_view(),
                           name='ordendetrabajo-autocomplete',
                       ),

                       url(
                           r'^ordendetrabajoventaautocomplete/$',
                           OrdenDeTrabajoVentaAutocomplete.as_view(),
                           name='ordendetrabajo_venta-autocomplete',
                       ),

                       url(
                           r'^detalleordendetrabajoautocomplete/$',
                           DetalleOrdenDeTrabajoAutocomplete.as_view(),
                           name='detalleordendetrabajo-autocomplete',
                       ),

                       url(r'^getordendetrabajo/$',get_ordendetrabajo),
                       url(r'^get_detalle_ot_duracion/$', get_detalle_ot_duracion),

                       url(r'^$', produccion_presentacion),
                       )

retoqueria/urls.py
# -*- coding: utf-8 -*-


"""retoqueria URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
    url(r'^admin/clientes/', include('clientes.urls')),
    url(r'^admin/funcionarios/', include('funcionarios.urls')),
    url(r'^admin/proveedores/', include('proveedores.urls')),
    url(r'^admin/materiales/', include('materiales.urls')),

    url(r'^admin/depositos/', include('depositos.urls')),
    url(r'^admin/servicios/', include('servicios.urls')),

    url(r'^admin/produccion/', include('produccion.urls')),

    url(r'^admin/ventas/', include('ventas.urls')),

    url(r'^admin/', include(admin.site.urls)), 
    url(r'^chaining/', include('smart_selects.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ventas/urls.py
from django.conf.urls import patterns, include, url

from ventas.autocomplete import CajaAutocomplete
from ventas.reports import reporte_consolidado_pdf
from ventas.views import *


urlpatterns = [
    url(
        r'^caja-autocomplete/$',
        CajaAutocomplete.as_view(),
        name='caja-autocomplete',
    ),

    url(r'^venta/(?P<pk>\d+)/detail/$', VentaDetailView.as_view(), name='venta_det'),
    url(r'^venta/$', VentaListView.as_view(), name='venta_lis'),
    url(r'^$', ventas_presentacion),
    url(
        r'^reporte_consolidado_pdf/(?P<id>\w+)/$',
        reporte_consolidado_pdf,
        name='reporte_consolidado_pdf',
    ),
]

produccion/models.py
# -*- coding: utf-8 -*-

from django.contrib.contenttypes.models import ContentType
from django.db import models
from datetime import date, timedelta
from django.contrib.admin.models import LogEntry, CHANGE

from django.utils.encoding import force_unicode
from django.db.models.signals import post_save

from django.dispatch import receiver

from funcionarios.models import Funcionario, DetalleDeLiquidacion, Liquidacion

OT_PENDIENTE = 0
OT_PROCESO = 1
OT_PRODUCCION = 2
OT_TERMINADO = 3
OT_REVISADO = 4
OT_ENTREGADO = 5
OT_RECHAZADO = 6

ESTADO_OT = (
    (OT_PENDIENTE, 'Pendiente'),
    (OT_PROCESO, 'En Proceso'),
    (OT_PRODUCCION, 'En Produccion'),
    (OT_TERMINADO, 'Terminado'),
    (OT_REVISADO, 'Revisado'),
    (OT_ENTREGADO, 'Entregado'),
    (OT_RECHAZADO, 'Rechazado')
)


class OrdenDeTrabajo(models.Model):
    class Meta:
        permissions = (
            ("ver_ot_todos", "Puede ver la lista general de trabajos"),
            ("ver_ot_pendientes", "Puede ver la lista de trabajos pendientes"),
            ("ver_ot_proceso", "Puede ver la lista de trabajos en proceso"),
            ("ver_ot_produccion", "Puede ver la lista de trabajos en produccion"),
            ("ver_ot_terminados", "Puede ver la lista de trabajos terminados"),
            ("ver_ot_revisados", "Puede ver la lista de trabajos revisados"),
            ("ver_ot_entregados", "Puede ver la lista de trabajos entregados"),
            ("ver_ot_rechazados", "Puede ver la lista de trabajos rechazados"),
            ("ver_ot_entregas", "Puede ver la lista de Entregas Pendientes"),

            ("pasar_ot_proceso", "Puede pasar el trabajo al estado en proceso"),
            ("pasar_ot_produccion", "Puede pasar el trabajo al estado en produccion"),
            ("pasar_ot_terminado", "Puede pasar el trabajo al estado terminado"),
            ("pasar_ot_revisado", "Puede pasar el trabajo al estado revisado"),
            ("pasar_ot_entregado", "Puede pasar el trabajo al estado entregado"),
            ("pasar_ot_rechazado", "Puede pasar el trabajo al estado rechazado"),

            ("retroceder_ot_pendiente", "Puede retroceder el trabajo al estado pendiente"),
            ("retroceder_ot_proceso", "Puede retroceder el trabajo al estado en proceso"),
            ("retroceder_ot_produccion", "Puede retroceder el trabajo al estado en produccion"),
            ("retroceder_ot_terminado", "Puede retroceder el trabajo al estado terminado"),
            ("retroceder_ot_revisado", "Puede retroceder el trabajo al estado revisado"),
            ("retroceder_ot_entregado", "Puede retroceder el trabajo al estado entregado"),
            ("reprogramar_ot", "Puede reprogramar el trabajo rechazado"),

            ("asignar_modista", "Puede asignar una modista a la OT"),
        )

    revision = models.IntegerField(default=1, editable=False)

    fecha_de_ingreso = models.DateField(default=date.today)
    fecha_de_entrega = models.DateField(null=True)
    hora_de_entrega = models.TimeField(null=True, blank=True)
    dias_para_prueba = models.IntegerField(null=True, blank=True)
    dias_post_prueba = models.IntegerField(null=True, blank=True)
    cliente = models.ForeignKey("clientes.Cliente")
    prenda = models.CharField(max_length=300, null=True)
    estado = models.IntegerField(choices=ESTADO_OT, editable=False, default=OT_PENDIENTE)
    modista = models.ForeignKey('funcionarios.Funcionario', null=True, default=4)

    # opciones
    ninos = models.BooleanField(default=False, verbose_name="niños")
    express = models.BooleanField(default=False)
    con_forro = models.BooleanField(default=False)
    con_pedreria = models.BooleanField(default=False, verbose_name="con pedreria/encaje/lentejuela")
    gestion_de_compra = models.BooleanField(default=False)

    descuento = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    def __unicode__(self):
        return unicode("OT: " + str(self.id) + " - " + str(self.revision))

    def save(self, *args, **kwargs):
        if (self.pk is None) and (self.express is True):
            self.estado = OT_PRODUCCION
            self.fecha_de_entrega = date.today()
        super(OrdenDeTrabajo, self).save(*args, **kwargs)

    def get_duracion(self):
        duracion = 0
        for detalle in self.detalleordendetrabajo_set.all():
            duracion += detalle.servicio.duracion
            return duracion

    @property
    def vencida(self):
        return date.today() >= self.fecha_de_entrega


class DetalleOrdenDeTrabajo(models.Model):
    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'

    orden_de_trabajo = models.ForeignKey(OrdenDeTrabajo)
    categoria_servicio = models.ForeignKey("servicios.CategoriaDeServicio", verbose_name="Categoria de servicio",
                                           null=True)
    servicio = models.ForeignKey("servicios.Servicio")
    tela = models.ForeignKey("servicios.Tela")
    cantidad = models.DecimalField(max_digits=4, decimal_places=2, default=1)
    precio = models.DecimalField(max_digits=15, decimal_places=2)
    observaciones = models.TextField(null=True, blank=True)
    liquidado = models.BooleanField(default=False)

    def __str__(self):
        return '%s - %s [%s]' % (str(self.servicio), str(self.tela), str(self.orden_de_trabajo))

    def marcar_liquidado(self):
        detalle = DetalleDeLiquidacion.objects.filter(servicio_id=self.id).first()

        if detalle:
            self.liquidado = True

        else:
            self.liquidado = False
        super(DetalleOrdenDeTrabajo, self).save()


def get_fecha_de_taller():
    ordenes = OrdenDeTrabajo.objects.filter(estado__in=[OT_PROCESO, OT_PENDIENTE, OT_PRODUCCION])
    buscar = True
    delta = 1
    while buscar:
        fecha_de_taller = date.today() + timedelta(days=delta)
        if int(fecha_de_taller.strftime("%w")) == 0:
            delta += 1
        else:
            ots_con_misma_fecha_de_entrega = ordenes.filter(fecha_de_entrega=fecha_de_taller).count()
            if ots_con_misma_fecha_de_entrega >= 10:
                delta += 1
            elif ots_con_misma_fecha_de_entrega < 10:
                buscar = False

    return fecha_de_taller


def log_change(object, user, modista):
    LogEntry.objects.log_action(
        user_id=user,
        content_type_id=ContentType.objects.get_for_model(object).pk,
        object_id=object.pk,
        object_repr=force_unicode(object),
        action_flag=CHANGE,
        change_message='cambiada modista' + " a " + modista
    )

produccion/templates/asignar_modista_form.html
{% extends "admin/base_site.html" %}

{% block content %}
<div>
	<form action="" method="post">{% csrf_token %}
		<div align="center">

			<h2>Asignar Modista</h2>
			<br>

			{{ form.as_p }}

			<button type="submit" class="btn btn-success">Aceptar</button>
			<button type="button" onclick="window.history.back(); return false;" class="btn btn-danger">Cancelar</button>

		</div>
	</form>
</div>
{% endblock %}

{% block footer %}
{{ form.media }}
{% endblock %}

produccion/templates/ordendetrabajopendiente_list.html
{% extends 'admin/base_site.html'%}
{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
	<link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
	<link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}	
<script src="{% static 'chosen/chosen.jquery.js' %}"></script>
<script src="{% static 'chosen/docsupport/prism.js' %}"></script>

<script type="text/javascript" src="{% static 'js/jquery.maskedinput.min.js' %}"></script>


<script type="text/javascript">
	$(".chosen-select").chosen({
		disable_search_threshold: 0,
		no_results_text: "Sin resultados..",
		width: "300px",
		allow_single_deselect: true
	});
	$('.chosen-select').trigger('chosen:updated');

    jQuery(function($) {
        $(".date").mask("99/99/9999",{placeholder:"dd/mm/aaaa"});
    });


</script>
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de ordenes de trabajo pendientes</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>
							<th style="vertical-align:middle">
								<strong> Numero:</strong>	
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="99999" name="q" value="{{ q }}">
							</td>

							<th style="vertical-align:middle">
								<strong> Cliente:</strong>	
							</th>
							<td style="vertical-align:middle">
								<select class="chosen-select" data-placeholder="Seleccione un cliente.." name="cliente_id" value="{{ cliente_id }}" onchange="this.form.submit();">
									<option value=""></option>
									{% for cliente in clientes %}
									<option {% if cliente.pk == cliente_id %} selected {% endif %} value="{{ cliente.id }}">{{ cliente }}</option>
									{% endfor %}
								</select>
							</td>
						</tr>

						<tr>

							<th style="vertical-align:middle">
								<strong> Fecha de ingreso desde:</strong>	
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="date" placeholder="dd/mm/aaaa" name="fecha_de_ingreso_desde" value="{{ fecha_de_ingreso_desde }}">
							</td>


							<th style="vertical-align:middle">
								<strong> Fecha de ingreso hasta:</strong>	
							</th>
							<td style="vertical-align:middle" colspan="3">
								<input type="text" class="date" placeholder="dd/mm/aaaa" name="fecha_de_ingreso_hasta" value="{{ fecha_de_ingreso_hasta }}">
							</td>
						</tr>
						
						<tr>

							<th style="vertical-align:middle">
								<strong> Fecha de entrega desde:</strong>	
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="date" placeholder="dd/mm/aaaa" name="fecha_de_entrega_desde" value="{{ fecha_de_entrega_desde }}">
							</td>


							<th style="vertical-align:middle">
								<strong> Fecha de entrega hasta:</strong>	
							</th>
							<td style="vertical-align:middle" colspan="3">
								<input type="text" class="date" placeholder="dd/mm/aaaa" name="fecha_de_entrega_hasta" value="{{ fecha_de_entrega_hasta }}">
							</td>




							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/produccion/ordendetrabajo/" title="Limpiar Filtros"> 
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>

                        <tr>
							<th style="vertical-align:middle">
								<strong> Modista:</strong>
							</th>
							<td style="vertical-align:middle">
								<select class="chosen-select" data-placeholder="Seleccione una modista.." name="modista_id" value="{{ modista_id }}" onchange="this.form.submit();">
									<option value=""></option>
									{% for modista in modistas %}
									<option {% if modista.pk == modista_id %} selected {% endif %} value="{{ modista.id }}">{{ modista }}</option>
									{% endfor %}
								</select>
							</td>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">

            <button onclick="this.form.submit();" class="btn btn-danger pull-left" name="pdf_materiales" value="pdf_materiales" type="submit" title="Reporte de materiales">
				<i class="fa fa-file-pdf-o"></i>
			</button>

			<button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
				<i class="fa fa-file-excel-o"></i>
			</button>

			{% if perms.produccion.add_ordendetrabajo %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/produccion/ordendetrabajo/add/?next={{ request.path }}';" title="Agregar Venta">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}
	 
		</div>
	</form>


	<br></br>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Numero</th>
					<th>Fecha de ingreso</th>
                    <th>Fecha de Entrega</th>
					<th>Cliente</th>
                    <th>Modista</th>
					<th>Estado</th>
					<th>Acciones</th>		 
				</tr>
			</thead>

			<tbody>
				{% for ordendetrabajo in object_list %}
				<tr{% if ordendetrabajo.vencida %} style="background-color: #FFBBD1" {% endif %}>
					<td>{{ ordendetrabajo.id|separador_miles }}</td>
					<td>{{ ordendetrabajo.fecha_de_ingreso }}</td>
                    <td>{{ ordendetrabajo.fecha_de_entrega }}</td>
					<td>{{ ordendetrabajo.cliente }}</td>
                    <td>{{ ordendetrabajo.modista.nombres }}</td>
					<td>{{ ordendetrabajo.get_estado_display }}</td>

					<td>
						{% if perms.produccion.change_ordendetrabajo %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/produccion/ordendetrabajo/{{ ordendetrabajo.id }}/?next={{ request.path }}';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.produccion.delete_ordendetrabajo %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/produccion/ordendetrabajo/{{ ordendetrabajo.id }}/delete/?next={{ request.path }}';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}

						{% if perms.produccion.pasar_ot_proceso %}
						<button type="button" class="btn btn-default btn-xs" onclick="location.href='/admin/produccion/ordendetrabajo/{{ ordendetrabajo.id }}/pasarotproceso/?next={{ request.path }}';" title="Pasar al estado en proceso">
							<i class="fa fa-share"></i>
						</button>
						{% endif %}

                        {% if perms.produccion.asignar_modista %}
						<button type="button" class="btn btn-default btn-xs" onclick="location.href='/admin/produccion/ordendetrabajo/{{ ordendetrabajo.id }}/asignarmodista/?next={{ request.path }}';" title="Asignar modista">
							<i class="fa fa-user-plus"></i>
						</button>
						{% endif %}

						<button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/produccion/ordendetrabajo/{{ ordendetrabajo.id }}/detail/';" title="Detalle">
							<i class="fa fa-list-ol"></i>
						</button>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/produccion/ordendetrabajo/pendiente/?page={{ page_obj.previous_page_number }}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha_de_ingreso_desde={{ fecha_de_ingreso_desde }}&fecha_de_ingreso_hasta={{ fecha_de_ingreso_hasta }}&fecha_de_entrega_desde={{ fecha_de_entrega_desde }}&fecha_de_entrega_hasta={{ fecha_de_entrega_hasta }}&modista_id={{ modista_id }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/produccion/ordendetrabajo/pendiente/?page={{ page_obj.previous_page_number }}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha_de_ingreso_desde={{ fecha_de_ingreso_desde }}&fecha_de_ingreso_hasta={{ fecha_de_ingreso_hasta }}&fecha_de_entrega_desde={{ fecha_de_entrega_desde }}&fecha_de_entrega_hasta={{ fecha_de_entrega_hasta }}&modista_id={{ modista_id }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/produccion/ordendetrabajo/pendiente/?page={{ page }}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha_de_ingreso_desde={{ fecha_de_ingreso_desde }}&fecha_de_ingreso_hasta={{ fecha_de_ingreso_hasta }}&fecha_de_entrega_desde={{ fecha_de_entrega_desde }}&fecha_de_entrega_hasta={{ fecha_de_entrega_hasta }}&modista_id={{ modista_id }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/produccion/ordendetrabajo/pendiente/?page={{ page_obj.next_page_number }}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha_de_ingreso_desde={{ fecha_de_ingreso_desde }}&fecha_de_ingreso_hasta={{ fecha_de_ingreso_hasta }}&fecha_de_entrega_desde={{ fecha_de_entrega_desde }}&fecha_de_entrega_hasta={{ fecha_de_entrega_hasta }}&modista_id={{ modista_id }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/produccion/ordendetrabajo/pendiente/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha_de_ingreso_desde={{ fecha_de_ingreso_desde }}&fecha_de_ingreso_hasta={{ fecha_de_ingreso_hasta }}&fecha_de_entrega_desde={{ fecha_de_entrega_desde }}&fecha_de_entrega_hasta={{ fecha_de_entrega_hasta }}&modista_id={{ modista_id }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}