depositos/urls.py
from django.conf.urls import patterns, include, url
from depositos.autocomplete import *
from depositos.views import *
#from depositos.ajax import *


urlpatterns = [


    url(
        'detalleretiroautocomplete/$',
        DetalleRetiroAutocomplete.as_view(),
        name='detalleretiro-autocomplete',
    ),

    url(r'^deposito/$', DepositoListView.as_view(), name='deposito_lis'),
    url(r'^alta/$', AltaListView.as_view(), name='alta_lis'),
    url(r'^baja/$', BajaListView.as_view(), name='baja_lis'),
    url(r'^retiro/$', RetiroListView.as_view(), name='retiro_lis'),
    url(r'^devolucion/$', DevolucionListView.as_view(), name='devolucion_lis'),

    url(r'^alta/(?P<pk>\d+)/delete/$', AltaDeleteView.as_view(), name='alta_del'),
    url(r'^baja/(?P<pk>\d+)/delete/$', BajaDeleteView.as_view(), name='baja_del'),
    url(r'^retiro/(?P<pk>\d+)/delete/$', RetiroDeleteView.as_view(), name='retiro_del'),
    url(r'^devolucion/(?P<pk>\d+)/delete/$', DevolucionDeleteView.as_view(), name='devolucion_del'),

    url(
        'retiroautocomplete/$',
        RetiroAutocomplete.as_view(),
        name='retiro-autocomplete',
    ),


]

retoqueria/urls.py
# -*- coding: utf-8 -*-


"""retoqueria URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
    url(r'^admin/clientes/', include('clientes.urls')),
    url(r'^admin/funcionarios/', include('funcionarios.urls')),
    url(r'^admin/proveedores/', include('proveedores.urls')),
    url(r'^admin/materiales/', include('materiales.urls')),

    url(r'^admin/depositos/', include('depositos.urls')),
    url(r'^admin/servicios/', include('servicios.urls')),

    url(r'^admin/produccion/', include('produccion.urls')),

    url(r'^admin/ventas/', include('ventas.urls')),

    url(r'^admin/', include(admin.site.urls)), 
    url(r'^chaining/', include('smart_selects.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ventas/urls.py
from django.conf.urls import patterns, include, url

from ventas.autocomplete import CajaAutocomplete
from ventas.reports import reporte_consolidado_pdf
from ventas.views import *


urlpatterns = [
    url(
        r'^caja-autocomplete/$',
        CajaAutocomplete.as_view(),
        name='caja-autocomplete',
    ),

    url(r'^venta/(?P<pk>\d+)/detail/$', VentaDetailView.as_view(), name='venta_det'),
    url(r'^venta/$', VentaListView.as_view(), name='venta_lis'),
    url(r'^$', ventas_presentacion),
    url(
        r'^reporte_consolidado_pdf/(?P<id>\w+)/$',
        reporte_consolidado_pdf,
        name='reporte_consolidado_pdf',
    ),
]

depositos/models.py
# -*- coding: utf-8 -*-

from django.db import models
from datetime import date


# Create your models here.
class Deposito(models.Model):
	nombre = models.CharField(max_length=100)

	def __unicode__(self):
		return self.nombre




class Alta(models.Model):
	deposito = models.ForeignKey(Deposito)
	fecha = models.DateField(default=date.today)
	funcionario = models.ForeignKey("funcionarios.Funcionario")

	def __unicode__(self):
		return "[Nro.: " + str(self.id) + "] - fecha: " + self.fecha.strftime("%d/%m/%Y") 

class DetalleAlta(models.Model):
	alta = models.ForeignKey(Alta)
	material = models.ForeignKey("materiales.Material")
	cantidad = models.DecimalField(max_digits=15, decimal_places=2)
	motivo = models.CharField(max_length=500, null=True, blank=True)

	def __unicode__(self):
		return self.material.__unicode__()

	def save(self, *args, **kwargs):
		super(DetalleAlta, self).save(*args, **kwargs)
		self.material.actualizar_stock()

	def delete(self, *args, **kwargs):
		material = self.material
		alta = self.alta

		super(DetalleAlta, self).delete(*args, **kwargs)
		
		material.actualizar_stock()	
		detalles = DetalleAlta.objects.filter(alta_id=alta.id)
		if not detalles:
			alta.delete()

class Baja(models.Model):
	deposito = models.ForeignKey(Deposito)
	fecha = models.DateField(default=date.today)
	funcionario = models.ForeignKey("funcionarios.Funcionario")

	def __unicode__(self):
		return "[Nro.: " + str(self.id) + "] - fecha: " + self.fecha.strftime("%d/%m/%Y") 

class DetalleBaja(models.Model):
	baja = models.ForeignKey(Baja)
	material = models.ForeignKey("materiales.Material")
	cantidad = models.DecimalField(max_digits=15, decimal_places=2)
	motivo = models.CharField(max_length=500, null=True, blank=True)

	def __unicode__(self):
		return self.material.__unicode__()

	def save(self, *args, **kwargs):
		super(DetalleBaja, self).save(*args, **kwargs)
		self.material.actualizar_stock()

	def delete(self, *args, **kwargs):
		material = self.material
		baja = self.baja

		super(DetalleBaja, self).delete(*args, **kwargs)
		
		material.actualizar_stock()	
		detalles = DetalleBaja.objects.filter(baja_id=baja.id)
		if not detalles:
			baja.delete()

class Retiro(models.Model):
	fecha = models.DateField(default=date.today)
	funcionario = models.ForeignKey("funcionarios.Funcionario")

	def __unicode__(self):
		return "[Nro.: " + str(self.id) + "] - fecha: " + self.fecha.strftime("%d/%m/%Y") 

class DetalleRetiro(models.Model):
	retiro = models.ForeignKey(Retiro)
	detalle_orden_de_trabajo = models.ForeignKey("produccion.DetalleOrdenDeTrabajo", null=True, blank=True, verbose_name="trabajo")
	deposito = models.ForeignKey(Deposito)
	material = models.ForeignKey("materiales.Material")
	cantidad = models.DecimalField(max_digits=15, decimal_places=2)

	def __unicode__(self):
		return self.material.__unicode__()


	def save(self, *args, **kwargs):
		super(DetalleRetiro, self).save(*args, **kwargs)
		self.material.actualizar_stock()

	def delete(self, *args, **kwargs):
		material = self.material
		retiro = self.retiro

		super(DetalleRetiro, self).delete(*args, **kwargs)
		
		material.actualizar_stock()
		detalles = DetalleRetiro.objects.filter(retiro_id=retiro.id)
		if not detalles:
			retiro.delete()

class Devolucion(models.Model):
	fecha = models.DateField(default=date.today)
	funcionario = models.ForeignKey("funcionarios.Funcionario")
	retiro = models.ForeignKey(Retiro, null=True, blank=False)

	def __unicode__(self):
		return "[Nro.: " + str(self.id) + "] - fecha: " + self.fecha.strftime("%d/%m/%Y") 

class DetalleDevolucion(models.Model):
	devolucion = models.ForeignKey(Devolucion)
	detalle_retiro = models.ForeignKey(DetalleRetiro, verbose_name="Material", null=True, blank=False)
	cantidad = models.DecimalField(max_digits=15, decimal_places=2)
	deposito = models.ForeignKey(Deposito)


	def __unicode__(self):
		return self.detalle_retiro.material.__unicode__()

	def save(self, *args, **kwargs):
		super(DetalleDevolucion, self).save(*args, **kwargs)
		self.detalle_retiro.material.actualizar_stock()

	def delete(self, *args, **kwargs):
		material = self.detalle_retiro.material
		devolucion = self.devolucion

		super(DetalleDevolucion, self).delete(*args, **kwargs)
		
		material.actualizar_stock()	
		detalles = DetalleDevolucion.objects.filter(devolucion_id=devolucion.id)
		if not detalles:
			devolucion.delete()

depositos/views.py
from django.shortcuts import render, render_to_response
from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView

from django.views.generic.list import ListView
from django.db.models import Q

from django.contrib.auth.models import User

from depositos.models import *
from funcionarios.models import *

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from extra.globals import *

class DepositoListView(ListView):
    model = Deposito
    template_name = "deposito_list.html"

    def get_queryset(self):
        depositos = Deposito.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            depositos = depositos.filter( nombre__icontains=q )

        return depositos

    def get_context_data(self, **kwargs):
        context = super(DepositoListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(DepositoListView, self).dispatch(*args, **kwargs)


class AltaListView(ListView):
    model = DetalleAlta
    template_name = "alta_list.html"
    paginate_by = 30

    def get_queryset(self):
        altas = DetalleAlta.objects.all().order_by('-id')

        funcionario_id = self.request.GET.get('funcionario_id', '')
        if funcionario_id != '':
            altas = altas.filter(alta__funcionario_id=funcionario_id)

        deposito_id = self.request.GET.get('deposito_id', '')
        if deposito_id != '':
            altas = altas.filter(alta__deposito_id=deposito_id)

        q = self.request.GET.get('q', '')
        if q != '':
            altas = altas.filter( Q(material__descripcion__icontains=q) | Q(material__id__istartswith=q) )

        return altas

    def get_context_data(self, **kwargs):
        context = super(AltaListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        context['funcionarios'] = Funcionario.objects.all()
        context['funcionario_id'] = int(self.request.GET.get('funcionario_id','')) if (self.request.GET.get('funcionario_id','') != '') else ''
        context['depositos'] = Deposito.objects.all()
        context['deposito_id'] = int(self.request.GET.get('deposito_id','')) if (self.request.GET.get('deposito_id','') != '') else ''
        return context

    def render_to_response(self, context, **response_kwargs):
        if 'excel' in self.request.GET.get('excel', ''): 

            lista_datos=[]
            datos = self.get_queryset()
            for dato in datos:
                lista_datos.append([
                    dato.alta.fecha.strftime('%d/%m/%Y'),
                    dato.alta.deposito.nombre,
                    dato.material.__unicode__(),
                    separador_de_miles(dato.cantidad),
                    dato.motivo,
                    dato.alta.funcionario.get_full_name()
                ])

            titulos=[ 'Fecha', 'Deposito', 'Material', 'Cantidad', 'Motivo','Funcionario' ]
            return listview_to_excel(lista_datos,'Altas',titulos)
        
        return super(AltaListView, self).render_to_response(context, **response_kwargs)


    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(AltaListView, self).dispatch(*args, **kwargs)

class BajaListView(ListView):
    model = DetalleBaja
    template_name = "baja_list.html"
    paginate_by = 30

    def get_queryset(self):
        bajas = DetalleBaja.objects.all().order_by('-id')

        funcionario_id = self.request.GET.get('funcionario_id', '')
        if funcionario_id != '':
            bajas = bajas.filter(baja__funcionario_id=funcionario_id)

        deposito_id = self.request.GET.get('deposito_id', '')
        if deposito_id != '':
            bajas = bajas.filter(baja__deposito_id=deposito_id)

        q = self.request.GET.get('q', '')
        if q != '':
            bajas = bajas.filter( Q(material__descripcion__icontains=q) | Q(material__id__istartswith=q) )

        return bajas

    def get_context_data(self, **kwargs):
        context = super(BajaListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        context['funcionarios'] = Funcionario.objects.all()
        context['funcionario_id'] = int(self.request.GET.get('funcionario_id','')) if (self.request.GET.get('funcionario_id','') != '') else ''
        context['depositos'] = Deposito.objects.all()
        context['deposito_id'] = int(self.request.GET.get('deposito_id','')) if (self.request.GET.get('deposito_id','') != '') else ''
        return context

    def render_to_response(self, context, **response_kwargs):
        if 'excel' in self.request.GET.get('excel', ''): 

            lista_datos=[]
            datos = self.get_queryset()
            for dato in datos:
                lista_datos.append([
                    dato.baja.fecha.strftime('%d/%m/%Y'),
                    dato.baja.deposito.nombre,
                    dato.material.__unicode__(),
                    separador_de_miles(dato.cantidad),
                    dato.motivo,
                    dato.baja.funcionario.get_full_name()
                ])

            titulos=[ 'Fecha', 'Deposito', 'Material', 'Cantidad', 'Motivo','Funcionario' ]
            return listview_to_excel(lista_datos,'Bajas',titulos)
        
        return super(BajaListView, self).render_to_response(context, **response_kwargs)

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(BajaListView, self).dispatch(*args, **kwargs)

class RetiroListView(ListView):
    model = DetalleRetiro
    template_name = "retiro_list.html"
    paginate_by = 30

    def get_queryset(self):
        retiros = DetalleRetiro.objects.all().order_by('-id')

        funcionario_id = self.request.GET.get('funcionario_id', '')
        if funcionario_id != '':
            retiros = retiros.filter(retiro__funcionario_id=funcionario_id)

        deposito_id = self.request.GET.get('deposito_id', '')
        if deposito_id != '':
            retiros = retiros.filter(deposito_id=deposito_id)

        material = self.request.GET.get('material', '')
        if material != '':
            retiros = retiros.filter( 
                Q(material__descripcion__icontains=material) | Q(material__id__istartswith=material) 
            )

        orden_de_trabajo = self.request.GET.get('orden_de_trabajo', '')
        if orden_de_trabajo != '':
            retiros = retiros.filter( 
                #Q(orden_de_trabajo__nombre__icontains=orden_de_trabajo) | Q(orden_de_trabajo__id__istartswith=orden_de_trabajo) 
                orden_de_trabajo__id=orden_de_trabajo
            )

        return retiros

    def get_context_data(self, **kwargs):
        context = super(RetiroListView, self).get_context_data(**kwargs)
        context['material'] = self.request.GET.get('material','')
        context['orden_de_trabajo'] = self.request.GET.get('orden_de_trabajo','')
        context['funcionarios'] = Funcionario.objects.all()
        context['funcionario_id'] = int(self.request.GET.get('funcionario_id','')) if (self.request.GET.get('funcionario_id','') != '') else ''
        context['depositos'] = Deposito.objects.all()
        context['deposito_id'] = int(self.request.GET.get('deposito_id','')) if (self.request.GET.get('deposito_id','') != '') else ''
        return context

    def render_to_response(self, context, **response_kwargs):
        if 'excel' in self.request.GET.get('excel', ''): 

            lista_datos=[]
            datos = self.get_queryset()
            for dato in datos:
                lista_datos.append([
                    dato.retiro.fecha.strftime('%d/%m/%Y'),
                    dato.deposito.nombre,
                    dato.material.__unicode__(),
                    separador_de_miles(dato.cantidad),
                    dato.retiro.funcionario.get_full_name()
                ])

            titulos=[ 'Fecha', 'Deposito', 'Material', 'Cantidad','Funcionario' ]
            return listview_to_excel(lista_datos,'Retiros',titulos)
        
        return super(RetiroListView, self).render_to_response(context, **response_kwargs)

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(RetiroListView, self).dispatch(*args, **kwargs)

class DevolucionListView(ListView):
    model = DetalleDevolucion
    template_name = "devolucion_list.html"
    paginate_by = 30

    def get_queryset(self):
        devoluciones = DetalleDevolucion.objects.all().order_by('-id')

        funcionario_id = self.request.GET.get('funcionario_id', '')
        if funcionario_id != '':
            devoluciones = devoluciones.filter(devolucion__funcionario_id=funcionario_id)

        deposito_id = self.request.GET.get('deposito_id', '')
        if deposito_id != '':
            devoluciones = devoluciones.filter(deposito_id=deposito_id)

        material = self.request.GET.get('material', '')
        if material != '':
            devoluciones = devoluciones.filter(Q(detalle_retiro__material__descripcion__icontains=material) | Q(detalle_retiro__material__id__istartswith=material))

        retiro = self.request.GET.get('retiro', '')
        if retiro != '':
            devoluciones = devoluciones.filter( 
                #Q(retiro__nombre__icontains=retiro) | Q(retiro__id__istartswith=retiro) 
                devolucion__retiro__id=retiro
            )

        return devoluciones

    def get_context_data(self, **kwargs):
        context = super(DevolucionListView, self).get_context_data(**kwargs)
        context['material'] = self.request.GET.get('material','')
        context['retiro'] = self.request.GET.get('retiro','')

depositos/templates/alta_confirm_delete.html
{% extends "admin/base_site.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
	<h2>Esta seguro que desea eliminar el registro de alta?</h2><br>
	<p>Fecha: {{ object.alta.fecha }} </p><br>
	<p>Deposito: {{ object.alta.deposito }}</p><br>
	<p>Material: {{ object.material }}</p><br>
	<p>Cantidad: {{ object.cantidad }}</p><br>
	<p>Motivo: {{ object.motivo }}</p><br>

	<button type="submit" class="btn btn-success">Aceptar</button>
	<button type="button" onclick="window.history.back(); return false;" class="btn btn-danger">Cancelar</button>
</form>
{% endblock %}

depositos/templates/alta_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load humanize %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %} 
<script src="{% static 'chosen/chosen.jquery.js' %}"></script>
<script src="{% static 'chosen/docsupport/prism.js' %}"></script>

<script type="text/javascript">
    $(".chosen-select").chosen({
        disable_search_threshold: 0,
        no_results_text: "Sin resultados..",
        width: "80%",
        allow_single_deselect: true
    });
    $('.chosen-select').trigger('chosen:updated');
</script>
{% endblock %}

{% block content %}
    <form class="form" method="get">
        <h1>Lista de Altas</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                        <tr>
                        <th style="vertical-align:middle">
                            <strong> Material:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="search-query" placeholder="Descripcion o codigo.." name="q" value="{{ q }}">
                        </td>

                            <th style="vertical-align:middle">
                                <strong> Funcionario:</strong>  
                            </th>
                            <td style="vertical-align:middle">
                                <select class="chosen-select" data-placeholder="Seleccione un funcionario.." name="funcionario_id" value="{{ funcionario_id }}" onchange="this.form.submit();">
                                    <option value=""></option>
                                    {% for funcionario in funcionarios %}
                                    <option {% if funcionario.pk == funcionario_id %} selected {% endif %} value="{{ funcionario.id }}">{{ funcionario }}</option>
                                    {% endfor %}
                                </select>
                            </td>


                            <th style="vertical-align:middle">
                                <strong> Deposito:</strong>  
                            </th>
                            <td style="vertical-align:middle">
                                <select class="chosen-select" data-placeholder="Seleccione un deposito.." name="deposito_id" value="{{ deposito_id }}" onchange="this.form.submit();">
                                    <option value=""></option>
                                    {% for deposito in depositos %}
                                    <option {% if deposito.pk == deposito_id %} selected {% endif %} value="{{ deposito.id }}">{{ deposito }}</option>
                                    {% endfor %}
                                </select>
                            </td>

                            <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                                <a class="btn btn-info" href="/admin/depositos/alta" title="Limpiar Filtros">
                                    <i class="fa fa-undo"></i>
                                </a>
                                <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                            </th>
                        </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">
            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>

            {% if perms.depositos.add_alta %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/depositos/alta/add/';" title="Agregar Alta">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}
            
        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>Fecha</th>
                <th>Deposito</th>
                <th>Material</th>
                <th>Cantidad</th>
                <th>Motivo</th>
                <th>Funcionario</th>
                <th>Acciones</th>

            </tr>
            </thead>

            <tbody>
            {% for detallealta in object_list %}
                <tr>
                    <td>{{ detallealta.alta.fecha}}</td>
                    <td>{{ detallealta.alta.deposito }}</td>

                    <td>{{ detallealta.material }}</td>
                    <td>{{ detallealta.cantidad|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
                    <td>{{ detallealta.motivo }}</td>


                    <td>{{ detallealta.alta.funcionario }}</td>

                    <td>
                        {% if perms.depositos.change_alta %}
                            <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/depositos/alta/{{ detallealta.alta.id }}/';" title="Editar">
                                <i class="fa fa-pencil"></i>
                            </button>
                        {% endif %}

                        {% if perms.depositos.delete_alta %}
                            <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/depositos/alta/{{ detallealta.id }}/delete/';" title="Borrar">
                                <i class="fa fa-minus"></i>
                            </button>
                        {% endif %}

                        <!--
                        <button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/depositos/alta/{{ detallealta.alta.id }}/detail/';" title="Detalle">
                            <i class="fa fa-list-ol"></i>
                        </button>


						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/depositos/alta/{{ alta.id }}/print/';" title="Imprimir">
							<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
						</button>
						-->

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/depositos/alta/?page={{ page_obj.previous_page_number }}&q={{ q }}&funcionario_id={{ funcionario_id }}&deposito_id={{ deposito_id }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/depositos/alta/?page={{ page_obj.previous_page_number }}&q={{ q }}&funcionario_id={{ funcionario_id }}&deposito_id={{ deposito_id }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/depositos/alta/?page={{ page }}&q={{ q }}&funcionario_id={{ funcionario_id }}&deposito_id={{ deposito_id }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/depositos/alta/?page={{ page_obj.next_page_number }}&q={{ q }}&funcionario_id={{ funcionario_id }}&deposito_id={{ deposito_id }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/depositos/alta/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&funcionario_id={{ funcionario_id }}&deposito_id={{ deposito_id }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}

depositos/templates/baja_confirm_delete.html
{% extends "admin/base_site.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
	<h2>Esta seguro que desea eliminar el registro de baja?</h2><br>
	<p>Fecha: {{ object.baja.fecha }} </p><br>
	<p>Deposito: {{ object.baja.deposito }}</p><br>
	<p>Material: {{ object.material }}</p><br>
	<p>Cantidad: {{ object.cantidad }}</p><br>
	<p>Motivo: {{ object.motivo }}</p><br>

	<button type="submit" class="btn btn-success">Aceptar</button>
	<button type="button" onclick="window.history.back(); return false;" class="btn btn-danger">Cancelar</button>
</form>
{% endblock %}

depositos/templates/devolucion_confirm_delete.html
{% extends "admin/base_site.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
	<h2>Esta seguro que desea eliminar el registro de devolucion?</h2><br>
	<p>Fecha: {{ object.devolucion.fecha }} </p><br>
	<p>Deposito: {{ object.deposito }}</p><br>
	<p>Material: {{ object.detalle_retiro.material }}</p><br>
	<p>Cantidad: {{ object.cantidad }}</p><br>

	<button type="submit" class="btn btn-success">Aceptar</button>
	<button type="button" onclick="window.history.back(); return false;" class="btn btn-danger">Cancelar</button>
</form>
{% endblock %}

depositos/templates/retiro_confirm_delete.html
{% extends "admin/base_site.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
	<h2>Esta seguro que desea eliminar el registro de retiro?</h2><br>
	<p>Fecha: {{ object.retiro.fecha }} </p><br>
	<p>Deposito: {{ object.deposito }}</p><br>
	<p>Material: {{ object.material }}</p><br>
	<p>Cantidad: {{ object.cantidad }}</p><br>

	<button type="submit" class="btn btn-success">Aceptar</button>
	<button type="button" onclick="window.history.back(); return false;" class="btn btn-danger">Cancelar</button>
</form>
{% endblock %}