materiales/urls.py
from django.conf.urls import patterns, include, url
from materiales.autocomplete import *
from materiales.views import *

urlpatterns = [
    url(
        'unidaddemedidaautocomplete/$',
        UnidadDeMedidaAutocomplete.as_view(),
        name='unidaddemedida-autocomplete',
    ),

    url(
        'categoriadematerialautocomplete/$',
        CategoriaDeMaterialAutocomplete.as_view(),
        name='categoriadematerial-autocomplete',
    ),

    url(
        'materialautocomplete/$',
        MaterialAutocomplete.as_view(),
        name='material-autocomplete',
    ),


    url(r'^unidaddemedida/$', UnidadDeMedidaListView.as_view(), name='unidaddemedida_lis'),

    url(r'^categoriadematerial/$', CategoriaDeMaterialListView.as_view(), name='categoriadematerial_lis'),
    
    url(r'^material/$', MaterialListView.as_view(), name='material_lis'),
    url(r'^material/(?P<pk>\d+)/detail/$', MaterialDetailView.as_view(), name='material_det'),

    url(r'^$', materiales_presentacion),
]

retoqueria/urls.py
# -*- coding: utf-8 -*-


"""retoqueria URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
    url(r'^admin/clientes/', include('clientes.urls')),
    url(r'^admin/funcionarios/', include('funcionarios.urls')),
    url(r'^admin/proveedores/', include('proveedores.urls')),
    url(r'^admin/materiales/', include('materiales.urls')),

    url(r'^admin/depositos/', include('depositos.urls')),
    url(r'^admin/servicios/', include('servicios.urls')),

    url(r'^admin/produccion/', include('produccion.urls')),

    url(r'^admin/ventas/', include('ventas.urls')),

    url(r'^admin/', include(admin.site.urls)), 
    url(r'^chaining/', include('smart_selects.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ventas/urls.py
from django.conf.urls import patterns, include, url

from ventas.autocomplete import CajaAutocomplete
from ventas.reports import reporte_consolidado_pdf
from ventas.views import *


urlpatterns = [
    url(
        r'^caja-autocomplete/$',
        CajaAutocomplete.as_view(),
        name='caja-autocomplete',
    ),

    url(r'^venta/(?P<pk>\d+)/detail/$', VentaDetailView.as_view(), name='venta_det'),
    url(r'^venta/$', VentaListView.as_view(), name='venta_lis'),
    url(r'^$', ventas_presentacion),
    url(
        r'^reporte_consolidado_pdf/(?P<id>\w+)/$',
        reporte_consolidado_pdf,
        name='reporte_consolidado_pdf',
    ),
]

materiales/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.apps import apps

class UnidadDeMedida(models.Model):
    class Meta:
        verbose_name = "unidad de medida"
        verbose_name_plural = "unidades de medida"

    nombre = models.CharField(max_length=100)
    simbolo = models.CharField(max_length=10, blank=True, null=True, verbose_name="Símbolo")

    def __unicode__(self):
        return unicode(self.nombre)


class CategoriaDeMaterial(models.Model):
    class Meta:
        verbose_name = "categoría de materiales"
        verbose_name_plural = "categorías de materiales"

    nombre = models.CharField(max_length=100)
    activo = models.BooleanField(default=True)

    def __unicode__(self):
        return unicode(self.nombre)

class Material(models.Model):
    class Meta:
        verbose_name_plural = "materiales"

    descripcion = models.CharField(max_length=150, verbose_name="descripción")
    unidad_de_medida = models.ForeignKey(UnidadDeMedida)
    categoria = models.ForeignKey(CategoriaDeMaterial, verbose_name="categoría")

    proveedores = models.ManyToManyField("proveedores.Proveedor", blank=True)

    stock_actual = models.DecimalField(max_digits=15, decimal_places=2, default=0, editable=False)
    stock_minimo = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    def __unicode__(self):
        return unicode(self.descripcion) 

    def actualizar_stock(self):
        
        cantidad = 0

        detalles_altas = apps.get_model("depositos","DetalleAlta").objects.filter(material_id = self.id)
        for detalle in detalles_altas:
            cantidad = cantidad + detalle.cantidad

        detalles_bajas = apps.get_model("depositos","DetalleBaja").objects.filter(material_id = self.id)
        for detalle in detalles_bajas:
            cantidad = cantidad - detalle.cantidad

        detalles_retiros = apps.get_model("depositos","DetalleRetiro").objects.filter(material_id = self.id)
        for detalle in detalles_retiros:
            cantidad = cantidad - detalle.cantidad

        detalles_devoluciones = apps.get_model("depositos","DetalleDevolucion").objects.filter(detalle_retiro__material__id = self.id)
        for detalle in detalles_devoluciones:
            cantidad = cantidad + detalle.cantidad

        self.stock_actual = cantidad
        self.save()

materiales/forms.py
from dal import autocomplete
from django import forms
from materiales.models import Material

class MaterialForm(forms.ModelForm):
	class Meta:
		model = Material
		fields = ('__all__')
		widgets = { 
			"unidad_de_medida": autocomplete.ModelSelect2(url='unidaddemedida-autocomplete'),
			"categoria": autocomplete.ModelSelect2(url='categoriadematerial-autocomplete'),
			"stock_minimo":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
		}

materiales/views.py
from django.shortcuts import render, render_to_response

# Create your views here.
from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from django.db.models import Q

from materiales.models import UnidadDeMedida, CategoriaDeMaterial, Material
from extra.globals import *

# Create your views here.

class UnidadDeMedidaListView(ListView):
    model = UnidadDeMedida
    template_name = "unidaddemedida_list.html"
    paginate_by = 30

    def get_queryset(self):
        unidadesdemedidas = UnidadDeMedida.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            unidadesdemedidas = unidadesdemedidas.filter(nombre__icontains=q)

        return unidadesdemedidas.order_by("nombre")

    def get_context_data(self, **kwargs):
        context = super(UnidadDeMedidaListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(UnidadDeMedidaListView, self).dispatch(*args, **kwargs)



class CategoriaDeMaterialListView(ListView):
    model = CategoriaDeMaterial
    template_name = "categoriadematerial_list.html"
    paginate_by = 30

    def get_queryset(self):
        categoriasdemateriales = CategoriaDeMaterial.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            categoriasdemateriales = categoriasdemateriales.filter( Q(nombre__icontains=q) | Q(id__startswith=q) )
        return categoriasdemateriales.order_by("nombre")

    def get_context_data(self, **kwargs):
        context = super(CategoriaDeMaterialListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(CategoriaDeMaterialListView, self).dispatch(*args, **kwargs)



class MaterialListView(ListView):
    model = Material
    template_name = "material_list.html"
    paginate_by = 30

    def get_queryset(self):
        materiales = Material.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            materiales = materiales.filter( Q(descripcion__icontains=q) | Q(id__startswith=q) )

        categoria_id=self.request.GET.get('categoria_id','')
        if categoria_id !='':
            materiales = materiales.filter(categoria_id = categoria_id)

        return materiales.order_by("descripcion")

    def get_context_data(self, **kwargs):
        context = super(MaterialListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        context['categorias'] = CategoriaDeMaterial.objects.all()
        context['categoria_id'] = int(self.request.GET.get('categoria_id','')) if (self.request.GET.get('categoria_id','') != '') else ''
        return context

    def render_to_response(self, context, **response_kwargs):
        if 'excel' in self.request.GET.get('excel', ''): 

            lista_datos=[]
            datos = self.get_queryset()
            for dato in datos:
                lista_datos.append([
                    dato.descripcion,
                    dato.unidad_de_medida.nombre if dato.unidad_de_medida != None else '',
                    dato.categoria.nombre if dato.categoria != None else '',
                    separador_de_miles(dato.stock_actual),
                    separador_de_miles(dato.stock_minimo),

                ])

            titulos=[ 
                'Descripcion', 
                'Unidad de medida', 
                'Categoria', 
                'Stock actual',
                'Stock minimo',
            ]
            return listview_to_excel(lista_datos,'Materiales',titulos)
        
        return super(MaterialListView, self).render_to_response(context, **response_kwargs)

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(MaterialListView, self).dispatch(*args, **kwargs)

class MaterialDetailView(DetailView):
    model = Material
    template_name = "material_detail.html"

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(MaterialDetailView, self).dispatch(*args, **kwargs)

def materiales_presentacion(request):
    context = RequestContext(request)
    titulo="MATERIALES"
    descripcion=".."
    return render_to_response('admin/presentacion.html', {'titulo': titulo, 'descripcion': descripcion}, context)

materiales/templates/categoriadematerial_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
{% endblock %}

{% block extrajs %}	
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Categorias</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>
							<th style="vertical-align:middle">
								<strong> Buscar:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Nombre o codigo.." name="q" value="{{ q }}">
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/materiales/categoriadematerial" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			{% if perms.materiales.add_categoriadematerial %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/materiales/categoriadematerial/add/';" title="Agregar Categoria">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}

			<!--
			<button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
				<i class="fa fa-file-excel-o"></i>
			</button>
			--> 
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Codigo</th>
					<th>Nombre</th>
					<th>Activo</th>
					<th>Acciones</th>
				</tr>
			</thead>

			<tbody>
				{% for categoriadematerial in object_list %}
				<tr>
					<td>{{ categoriadematerial.id }}</td>
					<td>{{ categoriadematerial.nombre }}</td>
					<td>{{ categoriadematerial.activo }}</td>

					<td>
						{% if perms.materiales.change_categoriadematerial %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/materiales/categoriadematerial/{{ categoriadematerial.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.materiales.delete_categoriadematerial %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/materiales/categoriadematerial/{{ categoriadematerial.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}


					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/materiales/categoriadematerial/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/materiales/categoriadematerial/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/materiales/categoriadematerial/?page={{ page }}&q={{ q }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/materiales/categoriadematerial/?page={{ page_obj.next_page_number }}&q={{ q }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/materiales/categoriadematerial/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}

materiales/templates/material_detail.html
{% extends "admin/base_site.html" %}
{% load humanize %}

{% block content %}
<h1>Datos del Material</h1>
<table class="table table-striped table-filter" summary="Datos del Material.">
	<tbody>
		<tr>
			<th scope="row"> ID </th>
			<td> {{ object.id }} </td>
		</tr>

		<tr>
			<th scope="row"> Descripcion </th>
			<td> {{ object.descripcion }} </td>
		</tr>

		<tr>
			<th scope="row"> Unidad de medida </th>
			<td> {{ object.unidad_de_medida }} </td>
		</tr>

		<tr>
			<th scope="row"> Categoria </th>
			<td> {{ object.categoria }} </td>
		</tr>

		<tr>
			<th scope="row"> Stock actual </th>
			<td> {{ object.stock_actual|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }} </td>
		</tr>

		<tr>
			<th scope="row"> Stock minimo </th>
			<td> {{ object.stock_minimo|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }} </td>
		</tr>

	</tbody>
</table>

{% if object.proveedores.all %}
<table id="result_list" class="table table-striped table-bordered table-hover table-condensed">
	<caption><h1>Proveedores</h1></caption>

	<thead>
		<tr>
			<th>Nombre</th>
		</tr>
	</thead>

	<tbody>
		{% for proveedor in object.proveedores.all %}
		<tr>
			<td>{{ proveedor }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endif %}

<button type="button" class="btn btn-primary" onclick="window.history.back(); return false;">Volver</button>

{% endblock %}

materiales/templates/material_list.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>

    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
    <form class="form" method="get">
        <h1>Lista de Materiales</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Buscar:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="search-query" placeholder="Nombre o ID.." name="q" value="{{ q }}">
                        </td>

                        <th style="vertical-align:middle">
                            <strong> Categoria:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select class="chosen-select" data-placeholder="Seleccione un categoria.." name="categoria_id" value="{{ categoria_id }}" onchange="this.form.submit();">
                                <option value=""></option>
                                {% for categoria in categorias %}
                                    <option {% if categoria.pk == categoria_id %} selected {% endif %} value="{{ categoria.id }}">{{ categoria }}</option>
                                {% endfor %}
                            </select>
                        </td>

                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/materiales/material" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">

            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>

            {% if perms.materiales.add_material %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/materiales/material/add/';" title="Agregar Material">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}

        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>ID</th>
                <th>Descripcion</th>
                <th>Unidad de medida</th>
                <th>Categoria</th>
                <th>Stock actual</th>
                <th>Stock minimo</th>
                <th>Acciones</th>

            </tr>
            </thead>

            <tbody>
            {% for material in object_list %}
                <tr>
                    <td>{{ material.id }}</td>
                    <td>{{ material.descripcion }}</td>
                    <td>{{ material.unidad_de_medida }}</td>
                    <td>{{ material.categoria }}</td>
                    <td>{{ material.stock_actual|floatformat:"0"|intcomma|default_if_none:"&nbsp;"  }}</td>
                    <td>{{ material.stock_minimo|floatformat:"0"|intcomma|default_if_none:"&nbsp;"  }}</td>

                    <td>
                        {% if perms.materiales.change_material %}
                            <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/materiales/material/{{ material.id }}/';" title="Editar">
                                <i class="fa fa-pencil"></i>
                            </button>
                        {% endif %}

                        {% if perms.materiales.delete_material %}
                            <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/materiales/material/{{ material.id }}/delete/';" title="Borrar">
                                <i class="fa fa-minus"></i>
                            </button>
                        {% endif %}


                        <button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/materiales/material/{{ material.id }}/detail/';" title="Detalle">
                            <i class="fa fa-list-ol"></i>
                        </button>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/materiales/material/?page={{ page_obj.previous_page_number }}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/materiales/material/?page={{ page_obj.previous_page_number }}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/materiales/material/?page={{ page }}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/materiales/material/?page={{ page_obj.next_page_number }}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/materiales/material/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&categoria_id={{ categoria_id }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}

materiales/templates/unidaddemedida_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
{% endblock %}

{% block extrajs %}	
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Unidades de Medida</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>
							<th style="vertical-align:middle">
								<strong> Buscar:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Nombre.." name="q" value="{{ q }}">
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/materiales/unidaddemedida/" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			{% if perms.materiales.add_unidaddemedida %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/materiales/unidaddemedida/add/';" title="Agregar Unidad de Medida">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}

			<!--
			<button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
				<i class="fa fa-file-excel-o"></i>
			</button>
			--> 
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>S&iacutembolo</th>
					<th>Acciones</th>
				</tr>
			</thead>

			<tbody>
				{% for unidaddemedida in object_list %}
				<tr>
					<td>{{ unidaddemedida.nombre }}</td>
					<td>{{ unidaddemedida.simbolo}}</td>
					<td>
						{% if perms.materiales.change_unidaddemedida %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/materiales/unidaddemedida/{{ unidaddemedida.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.materiales.delete_unidaddemedida %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/materiales/unidaddemedida/{{ unidaddemedida.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}


					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/materiales/unidaddemedida/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/materiales/unidaddemedida/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/materiales/unidaddemedida/?page={{ page }}&q={{ q }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/materiales/unidaddemedida/?page={{ page_obj.next_page_number }}&q={{ q }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/materiales/unidaddemedida/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}